### ISSUE TITLE
When you complete the website?

### ISSUE THREAD

**Issue by Mahisokhary** [MPBCoder/mpbcoder.github.io#7]
i`m waiting to see result!

**Comment by MPBCoder** [comment]
i stopped programming for about a year, but about 2 week I started again and I'm reviewing html, css. 
(also learning neovim :))
my goal to after learning tailwind refactor that... (about a 6 month...)

**Comment by Mahisokhary** [comment]
> i stopped programming for about a year, but about 2 week ago I started again and I'm reviewing html, css. (also learning neovim :)) my goal to after learning tailwind refactor that... (about a 6 month...)

im happy that you are back
Ancient netherite never die :))
